"""deterministic markdown renderer for the intelligence report.

fixed layout rules -> the same dataset always yields the same document. produces a
report titled ASHERIN INTELLIGENCE AGENCY / INTELLIGENCE ASSESSMENT with a source
register, findings with confidence, entity resolution table, evidence-graph summary,
contradictions, unresolved questions, and a reproducibility footer.

a clear notice marks this as a private analytical report, not an official government
document.
"""

from __future__ import annotations

from .model import ReportDataset

_BAR_FULL = "#"
_BAR_EMPTY = "."


def _confidence_bar(score: float, width: int = 10) -> str:
    filled = max(0, min(width, round(score * width)))
    return f"[{_BAR_FULL * filled}{_BAR_EMPTY * (width - filled)}] {int(round(score * 100))}%"


def render_markdown(ds: ReportDataset) -> str:
    lines: list[str] = []
    a = lines.append

    subject_name = ds.subject.get("name") or (ds.subject.get("usernames") or ["unknown"])[0]

    a(f"# {ds.agency}")
    a("## intelligence assessment")
    a("")
    a(f"- subject: **{subject_name}**")
    a(f"- report id: `{ds.report_id}`")
    a(f"- generated: {ds.generated_at}")
    a(f"- mode: {ds.methodology.get('mode')}")
    a(f"- overall confidence: **{ds.overall_band}** {_confidence_bar(ds.overall_confidence)}")
    a("")
    a("> private analytical report generated by the joseph engine. deterministic, non-ai. "
      "not an official government intelligence product.")
    a("")

    a("---")
    a("### executive assessment")
    a("")
    a(ds.executive_assessment)
    a("")

    # subject profile
    a("---")
    a("### subject profile")
    a("")
    for key in ("name", "usernames", "emails", "organizations", "locations", "occupations", "domains"):
        val = ds.subject.get(key)
        if val:
            shown = val if isinstance(val, str) else ", ".join(val)
            a(f"- {key}: {shown}")
    a("")

    # key findings
    a("---")
    a("### key findings")
    a("")
    if ds.findings:
        for f in ds.findings:
            a(f"- `{f['id']}` [{f['band']}] {f['claim']}")
            a(f"    - epistemic: {f['epistemic']} · corroboration: {f['corroboration']} · confidence {f['confidence']:.2f}")
            for ev in f.get("evidence", [])[:3]:
                a(f"    - evidence: {ev}")
    else:
        a("no findings -> live collection not executed or no evidence correlated.")
    a("")

    # entity resolution
    a("---")
    a("### identity / entity resolution")
    a("")
    if ds.entities:
        a("| verdict | kind | value | surface | score | features |")
        a("|---|---|---|---|---|---|")
        for e in ds.entities[:30]:
            feats = "; ".join(e.get("features", [])) or "-"
            a(f"| {e['verdict']} | {e['kind']} | {e['value']} | {e.get('surface') or '-'} | {e['score']:.2f} | {feats} |")
    else:
        a("no entities extracted -> plan-only mode or empty result set.")
    a("")

    # evidence graph
    a("---")
    a("### evidence graph")
    a("")
    gs = ds.graph_summary
    a(f"- nodes: {gs.get('nodes', 0)} · edges: {gs.get('edges', 0)}")
    if gs.get("top"):
        a("- most connected nodes:")
        for n in gs["top"]:
            a(f"    - [{n['kind']}] {n['label']} (degree {n['degree']})")
    a("")

    # query family
    a("---")
    a("### ranked query family")
    a("")
    a("the deterministic search plan. higher rank = higher expected information gain.")
    a("")
    for q in ds.query_family:
        a(f"{q['rank']}. `{q['google']}`")
        a(f"    - strategy: {q['strategy']} · score {q['score']:.2f} · {q['objective']}")
        a(f"    - google: {q['urls'].get('google')}")
        a(f"    - bing: {q['urls'].get('bing')}")
        a(f"    - ddg: {q['urls'].get('ddg')}")
    a("")

    # source register
    a("---")
    a("### source register")
    a("")
    if ds.sources:
        for i, s in enumerate(ds.sources, start=1):
            a(f"[{i:03d}] {s['title'] or s['url']}")
            a(f"      {s['url']}")
            a(f"      relevance {s['relevance']:.2f} · corroboration {s['corroboration']} · {', '.join(s['strategies'][:4])}")
    else:
        a("no sources -> collection not executed.")
    a("")

    # contradictions + unresolved
    a("---")
    a("### contradictions")
    a("")
    if ds.contradictions:
        for c in ds.contradictions:
            a(f"- {c}")
    else:
        a("none detected.")
    a("")

    a("### unresolved questions")
    a("")
    if ds.unresolved:
        for u in ds.unresolved:
            a(f"- {u}")
    else:
        a("none recorded.")
    a("")

    # methodology + reproducibility
    a("---")
    a("### methodology")
    a("")
    a(f"- engine: joseph v{ds.engine_version} (non-ai, deterministic)")
    a(f"- stages: {' -> '.join(ds.methodology.get('stages', []))}")
    a(f"- boundary: {ds.methodology.get('boundary')}")
    a("")
    a("### reproducibility")
    a("")
    a(f"- seed fingerprint: `{ds.seed_fingerprint}`")
    a(f"- dataset hash: `{ds.data_hash}`")
    a(f"- report id: `{ds.report_id}`")
    a("")

    return "\n".join(lines)
